[build]
  publish = "dist"        # or "build" if using React
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://your-api.com"
  REACT_APP_API_URL = "https://your-api.com"
